apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "cluster-hml-ec2"
  environment:
    cluster_type: ec2
    domain: vkpr.platform.vee.codes
    public_ip: 52.2.22.95
  annotations:
    github.com/project-slug: veecode-homolog/cluster-hml-ec2
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: cluster-hml-ec2
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,terraform-destroy.yml,deploy-dashboard
    cluster/instructions: "ssh -i ./key-pair.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} \n\"mkdir -p .kube && k3d kubeconfig get ${CLUSTER_NAME} > ~/.kube/config\"\nscp -i ./key-pair.pem ${EC2_USER}@${EC2_HOST}:~/.kube/config ./config\nyq e 'del(.clusters[0].cluster.certificate-authority-data)' -i ~/.kube/config\nyq e '.clusters[0].cluster.insecure-skip-tls-verify=true' config -i\nyq e '.clusters[0].cluster.server = \"https://${EC2_HOST}:38517\"' config -i\n"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
